---
title: "Untitled"
author: "Inas Zaizafun Satira/221810340/3SD1"
date: "12/3/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(e1071)
library(caret)
```
```{r}
sonar <- read_csv("D:/DOCUMENT/POLITEKNIK STATISTIKA STIS/PERKULIAHAN/TINGKAT 3/SEMESTER 5/UTS/DATMIN/sonar.all-data", col_names = FALSE)
str(sonar)
```

```{r}
modelSVM <- svm(X61~., data=sonar)
summary(modelSVM)
```


```{r}
plot(modelSVM, data=sonar,
     Petal.Width~Petal.Length,
     slice= list(Sepal.Width = 3,
                 Sepal.Length = 4))
```

```{r}
pred <- predict(modelSVM, sonar)
confusionMatrix(table(Predicted = pred, Actual=sonar$X61))
```

```{r}
set.seed(123)
uts <- tune(svm, X61~., data=sonar,
                     ranges = list(epsilon = seq(0,1,0.1),
                                   cost = 2^(2:9)))
uts
```
```{r}
plot(uts)
```
```{r}
summary(uts)
```

```{r}
bestmodel <- uts$best.model
summary(bestmodel)
```

```{r}
pred <- predict(bestmodel, sonar)
confusionMatrix(table(Predicted = pred, Actual=sonar$X61))
```